### PR TITLE
Asset tag

### PR DESCRIPTION
**Pull request by cybertunnel**
Adds the ability to require asset tag to be entered by the end user and updates it in NVRAM and JSS with the entered value.
**Current issue:** SplashScreen pushes Admin Prompt behind it.

### CODE REVIEW

**Comment by ftiff** [comment]
Thanks for the PR! 

I could compile and launch it (in DEBUG so I can see the helper)

But I get the following error after entering my admin password:
```
2016-12-21 09:18:15.575820 CasperSplash[60866:4661279] Bless Error: Error Domain=CFErrorDomainLaunchd Code=4 "(null)"
Helper: Bundle Version => 1.0.4
2016-12-21 09:18:22.800453 CasperSplash[60866:4661859] Bless Error: Error Domain=CFErrorDomainLaunchd Code=4 "(null)"
XPCService error: %@ Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named io.fti.CasperSplash.helper was invalidated." UserInfo={NSDebugDescription=The connection to service named io.fti.CasperSplash.helper was invalidated.}
2016-12-21 09:18:22.800924 CasperSplash[60866:4661279] XPC Connection Invalidated
```

**Comment by ftiff** [comment]
ok pardon me, I didn't read the README.md.

I downloaded SMJobBlessUtil.py and installed it in the root folder.

Then I run the following command: ```./SMJobBlessUtil.py setreq /Users/ftiff/Library/Developer/Xcode/DerivedData/CasperSplash-ewggcbjnqxusjxbjxznkgfdrcrar/Build/Products/Debug/CasperSplash.app CasperSplash/Info.plist CasperSplashHelper/CasperSplashHelper-Info.plist```

On the JSS, I indeed have "Asset Tag: 12345". Well done!

Now… Asking the user for their credentials is a no-go. We need to figure a way to make it transparent. DEP supports users not being admins, and I personally dislike asking the user for its password.

Would you have an idea on how to change this behaviour?

**Comment by cybertunnel** [comment]
Was thinking I can trace the location of the helper, and have where the helper gets installed by the JSS first, then gets called on by the SplashScreen

**Comment by cybertunnel** [comment]
From the looks of it, the privileged helper has a plist that gets dropped in `/Library/LaunchDaemons/` with the contents of:
```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>io.fti.CasperSplash.helper</string>
	<key>MachServices</key>
	<dict>
		<key>io.fti.CasperSplash.helper</key>
		<true/>
	</dict>
	<key>Program</key>
	<string>/Library/PrivilegedHelperTools/io.fti.CasperSplash.helper</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Library/PrivilegedHelperTools/io.fti.CasperSplash.helper</string>
	</array>
</dict>
</plist>```
And is also copied to `/Library/PrivilegedHelperTools/` where it sits and is executed from.

**Comment by ftiff** [comment]
That makes sense, so you just need to install it, then run `launchctl load /Library/LaunchDaemon/io.fti.CasperSplash.helper.plist` as a postinstall, right?

**Comment by cybertunnel** [comment]
Exactly! Just got the packager to work, and also ran manually launchctl load command. Working on how to deploy via JSS

**Pull request closed without merging**
